Update bmi_calc.py
When compiled it is giving [AttributeError: 'float' object has no attribute '2f']. In order to fix it I added ":" instead of 0 in curly brackets. If I am wrong just let me know.